config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'images/index'
  get 'images/new'
  get 'images/delete'
  get 'images/create'

  get 'images/user/:user_id', to: 'images#user'

  resources :images

  root to: "images#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
   # mount_uploader :picture, PictureUploader
   validates :description, presence: true

   belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_devise_params, if: :devise_controller?

    def configure_devise_params
        devise_parameter_sanitizer.permit(:sign_up) do |user|
            user.permit(:name, :email, :password, :password_confirmation)
        end 
    end 
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  before_action :set_image, only: [:show, :edit, :update, :destroy]

  def index
    @images = Image.all.reverse.paginate(page: params[:page], per_page: 3)
  end

  def user
    #@user = User.find params[:user_id]
    #@images = Image.all.reverse
    #User.find params[:user_id] 
    #Image.where user_id: current_user.id
    #@user = User.where user_id: current_user.id
    if user_signed_in?
      @image = Image.where user_id: current_user.id
    end  
  end

  def new
    @image = Image.new
  end

  def create
    @image = current_user.images.new image_params
    @image.save

    if @image.save
      return redirect_to images_index_path
    end

    render :new
  end

  def show
  end

  def edit
  end

  def update
    @image.update image_params
    redirect_to images_index_path
  end
  
  
  def destroy
    @image.destroy
    redirect_to images_path
  end

  private
  def image_params
    params.require(:image).permit(:description)
  end

  def set_image
    @image = Image.find params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%- if @image.errors.any? %>
    <div class="alert alert-danger">
        <p class="alert-heading">Algo salió mal...</p>
    </div>
<% end %>
<div class="container">
    <div class="form-group">
        <%= form_for @image do |f| %>
            <%= f.label :description%>
            <%= f.text_field :description, class: 'form-control'%> <br />
                <%- if @image.errors[:description].any? %>
                    <span class="baadge badge-pill badge-danger">
                        <%= @image.errors[:description].first %>
                    </span>
                <% end%>
            <%= f.submit 'Guardar', class: 'btn btn-primary' %>
            <%= link_to  'Cancelar', images_index_path, class: 'btn btn-outline-danger'%>
        <% end %>
    </div>
</div>

app/views/images/_image.html.erb
<div class="col">
  <div class="card my-2" style="width: 18rem;">
    <img src="https://getuikit.com/v2/docs/images/placeholder_600x400.svg" class="card-img-top" alt="...">
    <div class="card-body">
      <p class="card-text"><%= image.description%></p>
          <%= link_to 'Editar', edit_image_path(image), :class=>"btn btn-outline-info mr-3"%>
          <%= link_to 'Eliminar', image, method: :delete,:class=>"btn btn-outline-danger" %>
    </div>
  </div>
</div>

app/views/images/create.html.erb
<h1>Images#create</h1>
<p>Find me in app/views/images/create.html.erb</p>

app/views/images/delete.html.erb
<h1>Images#delete</h1>
<p>Find me in app/views/images/delete.html.erb</p>

app/views/images/edit.html.erb
<p>Edit </p>
<%= render 'form'%>

app/views/images/index.html.erb
<div class="container">
    <div class="row">
        <%= render @images %>
    </div>
    <%= will_paginate @images %>
</div>

app/views/images/new.html.erb
<%- if user_signed_in? %>
    <p> Crear </p>
    <%= render 'form'%>
<% end %>

app/views/images/show.html.erb
<h1> <%= @image.description %> </h1>

app/views/images/user.html.erb
<% render  @user.images %>
<h1> <%= @image.description %> </h1>
<%= @user.name %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsgram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <%= link_to 'Nuevo', images_new_path, :class=> 'navbar-brand'%>
        <%= link_to 'Todos', images_index_path, :class=> 'navbar-brand'%>
          <%- if user_signed_in? %>
            <p>Bienvenido  <%= current_user.name %></p>
            <%= link_to 'Perfil', 'images/user',  :class=>"btn btn-outline-info mr-2" %>
            <%= link_to 'Salir', destroy_user_session_path, method: :delete, :class=>"btn btn-outline-danger" %>
          <% else%>
            <%= link_to 'Iniciar', new_user_session_path,  :class=>"btn btn-outline-info mr-2" %>
            <%= link_to 'Registrate', new_user_registration_path,  :class=>"btn btn-primary mr-2" %>
          <% end %>
      </nav>
       
    </div>
    <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>